"""v2

Revision ID: 70795d099e76
Revises: cad23666857b
Create Date: 2025-09-22 16:52:00.206286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70795d099e76'
down_revision: Union[str, Sequence[str], None] = 'cad23666857b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.add_column('bus_routes', sa.Column('route_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('bus_routes_bus_id_fkey'), 'bus_routes', type_='foreignkey')
    op.create_foreign_key(None, 'bus_routes', 'routes', ['route_id'], ['id'])
    op.drop_column('bus_routes', 'bus_id')
    op.add_column('buses', sa.Column('time_stop_in_over', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buses', 'time_stop_in_over')
    op.add_column('bus_routes', sa.Column('bus_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bus_routes', type_='foreignkey')
    op.create_foreign_key(op.f('bus_routes_bus_id_fkey'), 'bus_routes', 'buses', ['bus_id'], ['id'])
    op.drop_column('bus_routes', 'route_id')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
