"""v7

Revision ID: 85b0cef9daa7
Revises: bdad91746161
Create Date: 2025-09-23 18:27:25.393354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b0cef9daa7'
down_revision: Union[str, Sequence[str], None] = 'bdad91746161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bus_routes', sa.Column('travel_time', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bus_routes', 'travel_time')
    # ### end Alembic commands ###
