"""v4

Revision ID: bdad91746161
Revises: 70795d099e76
Create Date: 2025-09-22 19:41:00.450710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdad91746161'
down_revision: Union[str, Sequence[str], None] = '70795d099e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bus_routes', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bus_routes', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
