"""rename latitude/longitude to lat/lon

Revision ID: cad23666857b
Revises: a9d34eeecfd1
Create Date: 2025-09-21 21:21:38.316723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad23666857b'
down_revision: Union[str, Sequence[str], None] = 'a9d34eeecfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('stops', sa.Column('lon', sa.Float(), nullable=False))
    op.drop_column('stops', 'longitude')
    op.drop_column('stops', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('stops', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('stops', 'lon')
    op.drop_column('stops', 'lat')
    # ### end Alembic commands ###
